# Generated by Django 4.0.4 on 2022-04-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('date', models.TextField()),
                ('story', models.TextField()),
                ('community', models.TextField()),
                ('user', models.TextField()),
                ('storyID', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userFriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyID', models.TextField()),
                ('relation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userStoryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyID', models.TextField()),
                ('owner', models.TextField()),
                ('visibility', models.TextField()),
            ],
        ),
    ]
