# Generated by Django 4.0.4 on 2022-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='communities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.TextField()),
            ],
            options={
                'ordering': ['comm'],
            },
        ),
        migrations.CreateModel(
            name='storyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='userFriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyID', models.TextField()),
                ('relation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userStoryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyID', models.TextField()),
                ('owner', models.TextField()),
                ('visibility', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('date', models.TextField()),
                ('story', models.TextField()),
                ('community', models.TextField()),
                ('user', models.TextField()),
                ('storyID', models.TextField()),
                ('location', models.TextField()),
                ('status', models.TextField()),
                ('links', models.ManyToManyField(to='tmasTest.storylink')),
            ],
        ),
    ]
