# Generated by Django 4.0.3 on 2022-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('date', models.TextField()),
                ('story', models.TextField()),
                ('community', models.TextField()),
                ('user', models.TextField()),
                ('storyID', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
